using System.Text.Json.Serialization;
using OpenMetrc.Builder.Domain.AdditivesTemplates;
using OpenMetrc.Builder.Domain.AdditivesTemplates.Requests;
using OpenMetrc.Builder.Domain.CaregiversStatus;
using OpenMetrc.Builder.Domain.Employees;
using OpenMetrc.Builder.Domain.Facilities;
using OpenMetrc.Builder.Domain.Harvests;
using OpenMetrc.Builder.Domain.Harvests.Requests;
using OpenMetrc.Builder.Domain.Items;
using OpenMetrc.Builder.Domain.Items.Requests;
using OpenMetrc.Builder.Domain.LabTests;
using OpenMetrc.Builder.Domain.LabTests.Requests;
using OpenMetrc.Builder.Domain.Locations;
using OpenMetrc.Builder.Domain.Locations.Requests;
using OpenMetrc.Builder.Domain.Packages;
using OpenMetrc.Builder.Domain.Packages.Requests;
using OpenMetrc.Builder.Domain.PatientCheckIns;
using OpenMetrc.Builder.Domain.PatientCheckIns.Requests;
using OpenMetrc.Builder.Domain.Patients;
using OpenMetrc.Builder.Domain.Patients.Requests;
using OpenMetrc.Builder.Domain.PatientsStatus;
using OpenMetrc.Builder.Domain.PlantBatches;
using OpenMetrc.Builder.Domain.PlantBatches.Requests;
using OpenMetrc.Builder.Domain.Plants;
using OpenMetrc.Builder.Domain.Plants.Requests;
using OpenMetrc.Builder.Domain.ProcessingJob;
using OpenMetrc.Builder.Domain.ProcessingJob.Requests;
using OpenMetrc.Builder.Domain.RetailId;
using OpenMetrc.Builder.Domain.RetailId.Requests;
using OpenMetrc.Builder.Domain.Sales;
using OpenMetrc.Builder.Domain.Sales.Requests;
using OpenMetrc.Builder.Domain.Strains;
using OpenMetrc.Builder.Domain.Strains.Requests;
using OpenMetrc.Builder.Domain.Sublocations;
using OpenMetrc.Builder.Domain.Sublocations.Requests;
using OpenMetrc.Builder.Domain.Tags;
using OpenMetrc.Builder.Domain.Transfers;
using OpenMetrc.Builder.Domain.Transfers.Requests;
using OpenMetrc.Builder.Domain.Transporters;
using OpenMetrc.Builder.Domain.Transporters.Requests;
using OpenMetrc.Builder.Domain.UnitsOfMeasure;
using OpenMetrc.Builder.Domain.WasteMethods;

namespace OpenMetrc.Builder.Domain;

[JsonSerializable(typeof(OpenMetrc.Builder.Domain.AdditivesTemplates.ActiveIngredients))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.AdditivesTemplates.AdditiveTemplate))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.AdditivesTemplates.AdditiveTemplateActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.AdditivesTemplates.AdditiveTemplateById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.AdditivesTemplates.AdditiveTemplateInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.AdditivesTemplates.Requests.AdditiveTemplateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.Attributes))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.CaregiversStatus.CaregiverStatus))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.DeletePlantBatchRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.DeletePlantRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Destinations))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Employees.Employee))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Facilities.Facility))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Facilities.FacilityType))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestFinish))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.HarvestFinishRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestLocation))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.HarvestLocationRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestOnHold))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestPackage))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.HarvestPackageRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestPackageTesting))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.HarvestPackageTestingRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestRename))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.HarvestRenameRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestRestoreHarvestedPlant))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.HarvestRestoreHarvestedPlantRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestUnfinish))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.HarvestUnfinishRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestWaste))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.HarvestWasteRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestWasteType))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.Ingredients))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.RetailId.Issuances))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.Item))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.ItemActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.ItemBrand))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.Requests.ItemBrandRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.ItemById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.ItemCategories))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.ItemCategory))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.ItemFile))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.ItemFileById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.Requests.ItemFileRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.ItemInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.ItemPhoto))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.ItemPhotoById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.Requests.ItemPhotoRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.Requests.ItemRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.LabTestBatch))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.Requests.LabTestLabTestDocumentRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.LabTestRecord))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.Requests.LabTestRecordRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.LabTestResult))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.Requests.LabTestResultReleaseRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.LabTestType))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.LabTestTypes))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Employees.License))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Locations.Location))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Locations.LocationActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Locations.LocationById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Locations.LocationInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Locations.Requests.LocationRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Locations.LocationType))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Package))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageAdjust))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageAdjustReason))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageAdjustRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageByIdSourceHarvest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageByLabel))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageDecontaminateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageDonationFlagRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageDonationUnflagRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageExternalidRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageFinishRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageIntransit))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageItemRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageLabSample))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageLabTestRequiredRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageLocationRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageNoteRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageOnHold))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackagePlanting))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackagePlantingRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageRemediateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.Requests.Packages))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageTesting))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageTestingRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageTradeSampleFlagRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageTradeSampleUnflagRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageTransferred))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageUnfinishRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageUseByDateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Patients.Patient))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Patients.PatientActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Patients.PatientById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PatientCheckIns.PatientCheckIn))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PatientCheckIns.PatientCheckInLocation))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PatientCheckIns.Requests.PatientCheckInRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Patients.Requests.PatientRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PatientsStatus.PatientStatus))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Plant))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantAdditive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantAdditiveByLocation))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantAdditiveByLocationRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantAdditiveByLocationUsingtemplate))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantAdditiveByLocationUsingtemplateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantAdditiveRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantAdditiveUsingtemplate))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantAdditiveUsingtemplateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantAdjustRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatch))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchAdditive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchAdditiveRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchAdditiveUsingtemplate))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchAdditiveUsingtemplateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchAdjust))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchAdjustRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchGrowthPhase))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchGrowthPhaseRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchLocationRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchNameRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchPackage))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchPackageFromMotherPlant))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchPackageFromMotherPlantRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchPackageRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchPlanting))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchPlantingRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchSplit))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchSplitRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchStrainRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchTagRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchType))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchWaste))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchWasteRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantByLabel))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantFlowering))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantGrowthPhaseRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantHarvestRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantLocationRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantManicure))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantManicureRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantMergeRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantMother))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantMotherInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantMotherOnHold))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantOnHold))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantPlantBatchPackage))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantPlantBatchPackageRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantPlanting))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantPlantingRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantSplit))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantSplitRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantStrainRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantTagRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantVegetative))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantWaste))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantWasteByIdPackage))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantWasteByIdPlant))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantWasteMethodAll))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantWasteReason))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantWasteRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.ProcessingActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.ProcessingAdjust))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.Requests.ProcessingAdjustRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.ProcessingById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.ProcessingCreatePackage))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.Requests.ProcessingCreatePackageRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.Requests.ProcessingFinishRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.ProcessingInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.ProcessingJobType))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.ProcessingJobTypeActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.ProcessingJobTypeAttribute))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.ProcessingJobTypeCategory))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.ProcessingJobTypeInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.Requests.ProcessingJobTypeRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.ProcessingStart))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.Requests.ProcessingStartRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.Requests.ProcessingUnfinishRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.ProductCategory))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.ProductLabel))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.Requests.Results))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.RetailId.RetailidAssociate))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.RetailId.Requests.RetailidAssociateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.RetailId.RetailidGenerate))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.RetailId.Requests.RetailidGenerateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.RetailId.Requests.RetailidMergeRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.RetailId.RetailidPackageInfo))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.RetailId.Requests.RetailidPackageInfoRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.RetailId.RetailidReceiveByLabel))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.RetailId.RetailidReceiveQr))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.ReturnedPackages))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleCounty))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDelivery))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryCompleteRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryHubAcceptRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryHubDepartRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryHubRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryHubVerifyIdRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryRetailer))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryRetailerActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryRetailerById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryRetailerDepartRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryRetailerEnd))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryRetailerEndRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryRetailerInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryRetailerRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryRetailerRestock))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryRetailerRestockRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryRetailerSale))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryRetailerSaleRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryReturnReason))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SalePatientRegistrationLocation))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleReceipt))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleReceiptActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleReceiptById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleReceiptExternal))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleReceiptFinalizeRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleReceiptInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleReceiptRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleReceiptUnfinalizeRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.SourcePlantBatches))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Strains.Strain))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Strains.StrainActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Strains.StrainById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Strains.StrainInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Strains.Requests.StrainRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sublocations.Sublocation))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sublocations.SublocationActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sublocations.SublocationById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sublocations.SublocationInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sublocations.Requests.SublocationRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Tags.TagPackageAvailable))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Tags.TagPlantAvailable))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Tags.TagStaged))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.Transactions))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferByIdDelivery))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferDeliveryByIdPackage))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferDeliveryByIdPackageWholesale))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferDeliveryByIdTransporter))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferDeliveryByIdTransporterDetail))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferDeliveryPackageByIdRequiredLabTestBatch))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferExternalIncoming))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.Requests.TransferExternalIncomingRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferHub))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferIncoming))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferOutgoing))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferRejected))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferTemplateOutgoing))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferTemplateOutgoingByIdDelivery))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferTemplateOutgoingDeliveryByIdPackage))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferTemplateOutgoingDeliveryByIdTransporter))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferTemplateOutgoingDeliveryByIdTransporterDetail))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.Requests.TransferTemplateOutgoingRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferType))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.Requests.TransporterDetails))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transporters.TransporterDriver))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transporters.TransporterDriverById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transporters.Requests.TransporterDriverRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.Requests.Transporters))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transporters.TransporterVehicle))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transporters.TransporterVehicleById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transporters.Requests.TransporterVehicleRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.UnitsOfMeasure.UnitOfMeasureActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.UnitsOfMeasure.UnitOfMeasureInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.WasteMethods.WasteMethod))]
public partial class MetrcJsonSerializerContext : JsonSerializerContext { }
