using System.Text.Json.Serialization;
using OpenMetrc.Builder.Domain.CaregiversStatus;
using OpenMetrc.Builder.Domain.Employees;
using OpenMetrc.Builder.Domain.Facilities;
using OpenMetrc.Builder.Domain.Harvests;
using OpenMetrc.Builder.Domain.Harvests.Requests;
using OpenMetrc.Builder.Domain.Items;
using OpenMetrc.Builder.Domain.Items.Requests;
using OpenMetrc.Builder.Domain.LabTests;
using OpenMetrc.Builder.Domain.LabTests.Requests;
using OpenMetrc.Builder.Domain.Locations;
using OpenMetrc.Builder.Domain.Locations.Requests;
using OpenMetrc.Builder.Domain.Packages;
using OpenMetrc.Builder.Domain.Packages.Requests;
using OpenMetrc.Builder.Domain.PatientCheckIns;
using OpenMetrc.Builder.Domain.PatientCheckIns.Requests;
using OpenMetrc.Builder.Domain.Patients;
using OpenMetrc.Builder.Domain.Patients.Requests;
using OpenMetrc.Builder.Domain.PatientsStatus;
using OpenMetrc.Builder.Domain.PlantBatches;
using OpenMetrc.Builder.Domain.PlantBatches.Requests;
using OpenMetrc.Builder.Domain.Plants;
using OpenMetrc.Builder.Domain.Plants.Requests;
using OpenMetrc.Builder.Domain.ProcessingJob.Requests;
using OpenMetrc.Builder.Domain.Sales;
using OpenMetrc.Builder.Domain.Sales.Requests;
using OpenMetrc.Builder.Domain.Strains;
using OpenMetrc.Builder.Domain.Strains.Requests;
using OpenMetrc.Builder.Domain.Transfers;
using OpenMetrc.Builder.Domain.Transfers.Requests;
using OpenMetrc.Builder.Domain.UnitsOfMeasure;

namespace OpenMetrc.Builder.Domain;

[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.ActiveIngredients))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.CaregiversStatus.CaregiverStatus))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Destinations))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Employees.Employee))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Facilities.Facility))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Facilities.FacilityType))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.HarvestCreatePackageRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.HarvestCreatePackageTestingRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.HarvestFinishRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.HarvestMoveRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestOnHold))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.HarvestRemoveWasteRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.HarvestRenameRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.HarvestUnfinishRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.HarvestWasteType))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Harvests.Requests.Ingredients))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Item))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.ItemActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.ItemBrand))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.ItemById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.ItemCategory))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.Requests.ItemCreateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.ItemInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.Requests.ItemPhotoRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Items.Requests.ItemUpdateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.Requests.LabTestLabTestDocumentRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.Requests.LabTestRecordRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.LabTestResult))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.Requests.LabTestResultReleaseRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.LabTestType))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Employees.License))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Locations.LocationActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Locations.LocationById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Locations.Requests.LocationCreateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Locations.LocationType))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Locations.Requests.LocationUpdateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageAdjustReason))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageAdjustRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageByLabel))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageChangeItemRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageChangeLocationRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageChangeNoteRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageCreatePlantingRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageCreateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageCreateTestingRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageFinishRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.PackageOnHold))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageRemediateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.Requests.Packages))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.Requests.PackageUnfinishRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Patients.PatientActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Patients.Requests.PatientAddRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Patients.PatientById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PatientCheckIns.PatientCheckIn))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PatientCheckIns.PatientCheckInLocation))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PatientCheckIns.Requests.PatientCheckInRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PatientsStatus.PatientStatus))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Patients.Requests.PatientUpdateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Plant))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantAdditive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantAdditiveByLocationRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantAdditiveRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatch))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchAdditiveRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchAdjustRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchChangeGrowthPhaseRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchCreatePackageFromMotherPlantRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchCreatePackageRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchCreateplantingRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.PlantBatchInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchMovePlantBatchRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchSplitRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.PlantBatchWasteRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantByLabel))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantChangeGrowthPhaseRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantCreatePlantBatchPackageRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantCreatePlantingRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantFlowering))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantHarvestplantRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantManicureplantRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantMoveplantRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantOnHold))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantVegetative))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantWasteMethodAll))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.PlantWasteReason))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Plants.Requests.PlantWasteRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.Requests.ProcessingAdjustRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.Requests.ProcessingCreatePackageRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.Requests.ProcessingFinishRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.Requests.ProcessingJobTypeRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.Requests.ProcessingStartRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.ProcessingJob.Requests.ProcessingUnfinishRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Packages.ProductLabel))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.LabTests.Requests.Results))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.ReturnedPackages))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleCounty))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryCompleteRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryHubAcceptRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryHubDepartRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryHubRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryHubVerifyIdRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryRetailerActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryRetailerById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryRetailerDepartRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryRetailerEndRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryRetailerInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryRetailerRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryRetailerRestockRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleDeliveryRetailerSaleRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleDeliveryReturnReason))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SalePatientRegistrationLocation))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleReceiptActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleReceiptById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleReceiptInactive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleReceiptRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleTransaction))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.SaleTransactionByDateRange))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.SaleTransactionRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.PlantBatches.Requests.SourcePlantBatches))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Strains.StrainActive))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Strains.StrainById))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Strains.Requests.StrainCreateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Strains.Requests.StrainUpdateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Sales.Requests.Transactions))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferByIdDelivery))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferDeliveryByIdPackage))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferDeliveryByIdPackageWholesale))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferDeliveryByIdTransporter))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferDeliveryByIdTransporterDetail))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferDeliveryPackageByIdRequiredLabTestBatch))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.Requests.TransferExternalIncomingRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferIncoming))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferOutgoing))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferRejected))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferTemplate))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferTemplateByIdDelivery))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferTemplateDeliveryByIdPackage))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferTemplateDeliveryByIdTransporter))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferTemplateDeliveryByIdTransporterDetail))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.Requests.TransferTemplateRequest))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.TransferType))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.Transfers.Requests.Transporters))]
[JsonSerializable(typeof(OpenMetrc.Builder.Domain.UnitsOfMeasure.UnitOfMeasureActive))]
public partial class MetrcJsonSerializerContext : JsonSerializerContext { }
